import type { TranscriptEntry } from '@/db/schema';

// ---------------------------------------------------------------------------
// Types
// ---------------------------------------------------------------------------

interface HeroQuote {
  text: string;
  agentName: string;
  /** Colour from preset agent definition, if available. */
  agentColor?: string;
  /** Reaction badge counts (only present for most-reacted turn). */
  reactions?: { heart: number; fire: number };
}

interface BoutHeroProps {
  presetName: string;
  agents: { name: string; color: string }[];
  /** The shareLine generated by the LLM after the bout. */
  shareLine?: string | null;
  /** Full transcript to extract a fallback hero quote from. */
  transcript: TranscriptEntry[];
  /** Most-reacted turn data (from getMostReactedTurnIndex). */
  mostReactedTurn?: {
    turnIndex: number;
    heartCount: number;
    fireCount: number;
  } | null;
}

// ---------------------------------------------------------------------------
// Helper: resolve hero quote from available data
// ---------------------------------------------------------------------------

function resolveHeroQuote({
  transcript,
  shareLine,
  mostReactedTurn,
  agents,
}: BoutHeroProps): HeroQuote | null {
  // Priority 1: Most-reacted turn — the crowd's favourite
  if (mostReactedTurn) {
    const entry = transcript.find((t) => t.turn === mostReactedTurn.turnIndex);
    if (entry) {
      const agent = agents.find((a) => a.name === entry.agentName);
      return {
        text: entry.text,
        agentName: entry.agentName,
        agentColor: agent?.color,
        reactions: {
          heart: mostReactedTurn.heartCount,
          fire: mostReactedTurn.fireCount,
        },
      };
    }
  }

  // Priority 2: shareLine (LLM-generated summary)
  if (shareLine?.trim()) {
    return {
      text: shareLine.trim(),
      agentName: 'THE PIT',
    };
  }

  // Priority 3: First transcript entry with meaningful text
  const first = transcript.find((t) => t.text.trim().length > 20);
  if (first) {
    const agent = agents.find((a) => a.name === first.agentName);
    return {
      text: first.text,
      agentName: first.agentName,
      agentColor: agent?.color,
    };
  }

  return null;
}

// ---------------------------------------------------------------------------
// Component
// ---------------------------------------------------------------------------

/**
 * Above-the-fold hero section for bout replay pages.
 * Shows the best quote from the bout to hook viral visitors
 * before they scroll into the full transcript.
 */
export function BoutHero(props: BoutHeroProps) {
  const quote = resolveHeroQuote(props);
  if (!quote) return null;

  // Truncate very long quotes to keep the hero punchy
  const MAX_HERO_LEN = 280;
  const displayText =
    quote.text.length > MAX_HERO_LEN
      ? `${quote.text.slice(0, MAX_HERO_LEN).trimEnd()}...`
      : quote.text;

  return (
    <section className="border-b-2 border-accent/40 bg-black/80 px-6 py-10 md:py-14">
      <div className="mx-auto max-w-4xl">
        {/* Matchup badge */}
        <p className="text-xs uppercase tracking-[0.4em] text-accent">
          {props.presetName}
        </p>
        <div className="mt-2 flex flex-wrap gap-2 text-xs uppercase tracking-[0.3em] text-muted">
          {props.agents.map((agent, i) => (
            <span key={agent.name}>
              <span style={{ color: agent.color }}>{agent.name}</span>
              {i < props.agents.length - 1 && (
                <span className="mx-2 text-foreground/30">vs</span>
              )}
            </span>
          ))}
        </div>

        {/* Hero quote */}
        <blockquote className="mt-6 border-l-4 pl-5 md:pl-6" style={{ borderColor: quote.agentColor ?? 'var(--accent)' }}>
          <p className="text-lg leading-relaxed text-foreground/90 md:text-xl">
            &ldquo;{displayText}&rdquo;
          </p>
          <footer className="mt-3 flex flex-wrap items-center gap-3 text-xs uppercase tracking-[0.3em] text-muted">
            <span style={{ color: quote.agentColor }}>
              {quote.agentName}
            </span>
            {quote.reactions && quote.reactions.fire > 0 && (
              <span className="text-orange-400">
                🔥 {quote.reactions.fire}
              </span>
            )}
            {quote.reactions && quote.reactions.heart > 0 && (
              <span className="text-red-400">
                ♥ {quote.reactions.heart}
              </span>
            )}
          </footer>
        </blockquote>

        {/* Scroll nudge */}
        <p className="mt-6 text-[10px] uppercase tracking-[0.3em] text-muted">
          Scroll to read the full battle
        </p>
      </div>
    </section>
  );
}
