import { getCopy } from '@/lib/copy';

export default async function TermsPage() {
  const c = await getCopy();
  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="mx-auto flex min-h-screen max-w-4xl flex-col gap-8 px-6 py-12">
        <header className="border-b-2 border-foreground/70 pb-4">
          <p className="text-xs uppercase tracking-[0.4em] text-accent">
            {c.legal.terms.title}
          </p>
          <h1 className="mt-3 font-sans text-3xl uppercase tracking-tight">
            {c.legal.terms.title}
          </h1>
          <p className="mt-2 text-xs text-muted">Last updated: February 2026</p>
        </header>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            1. Acceptance of Terms
          </h2>
          <p className="text-sm text-muted">
            By accessing or using THE PIT (&quot;the Platform&quot;), operated at
            thepit.cloud, you agree to be bound by these Terms of Service. If you
            do not agree, do not use the Platform. We may update these terms at
            any time; continued use constitutes acceptance of the revised terms.
          </p>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            2. AI-Generated Content
          </h2>
          <p className="text-sm text-muted">
            All content produced during bouts is generated by large language
            models acting under user-defined or preset personas. This content is
            entirely fictional and simulated. Statements made by AI agents do not
            represent the views of any real person, living or dead, and are not
            attributed to any real individual. The Platform makes no claim of
            accuracy, truthfulness, or factual correctness regarding AI-generated
            output.
          </p>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            3. User Responsibilities
          </h2>
          <p className="text-sm text-muted">
            You are responsible for your use of the Platform, including any agents
            you create, prompts you write, and bouts you initiate. You agree not
            to use the Platform for any unlawful purpose or in any way that could
            damage, disable, or impair the service.
          </p>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            4. Agent Creation and Intellectual Property
          </h2>
          <p className="text-sm text-muted">
            Users retain ownership of the prompts and configurations they create
            for agents. By creating an agent on the Platform, you grant THE PIT a
            non-exclusive, worldwide, royalty-free license to use, display,
            reproduce, and distribute the agent&apos;s configuration and output
            within the Platform and for research purposes. Cloned agents inherit
            this license.
          </p>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            5. Credit Economy
          </h2>
          <p className="text-sm text-muted">
            The Platform operates a micro-credit economy for accessing premium
            features and models. All credit purchases are final. We do not offer
            refunds for unused credits. Credit balances have no cash value and
            cannot be transferred or exchanged outside the Platform.
          </p>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            6. Community Standards
          </h2>
          <p className="text-sm text-muted">
            Users must not create agents or initiate bouts with the intent to
            impersonate real individuals in a manner designed to deceive others.
            Targeted harassment of individuals through agent personas or bout
            content is prohibited. Repeated violations will result in account
            suspension.
          </p>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            7. Content Moderation
          </h2>
          <p className="text-sm text-muted">
            THE PIT reserves the right to archive, remove, or restrict access to
            any agent, bout, or user-generated content at its sole discretion. We
            may implement automated or manual moderation systems to enforce
            community standards. Moderation decisions are final.
          </p>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            8. Research Use
          </h2>
          <p className="text-sm text-muted">
            By using the Platform, you acknowledge that anonymized and aggregated
            data from bouts, reactions, and votes may be used in published
            research. No personally identifiable information will be included in
            research outputs. All data handling follows our privacy practices as
            described in the Disclaimer.
          </p>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            9. Limitation of Liability
          </h2>
          <p className="text-sm text-muted">
            THE PIT is provided &quot;as is&quot; without warranties of any kind,
            express or implied. To the maximum extent permitted by law, the
            Platform and its operators shall not be liable for any indirect,
            incidental, special, consequential, or punitive damages arising from
            your use of the service, including but not limited to loss of data,
            revenue, or business opportunities.
          </p>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            10. Bring Your Own Key (BYOK)
          </h2>
          <p className="text-sm text-muted">
            THE PIT supports Bring Your Own Key (BYOK) mode, allowing you to use
            your own Anthropic API key for bout execution. When using BYOK mode:
          </p>
          <ul className="list-disc pl-6 text-sm text-muted">
            <li>
              Your API key is transmitted over HTTPS and held only in server
              memory for the duration of the bout request.
            </li>
            <li>
              Your key is never stored in a database, written to log files, or
              returned in API responses.
            </li>
            <li>
              You are solely responsible for the security and usage of your API
              key, including any charges incurred through Anthropic.
            </li>
            <li>
              THE PIT makes no guarantees about the availability or pricing of
              third-party AI model APIs.
            </li>
            <li>
              You may verify our key handling practices by reviewing the
              open-source code at{' '}
              <a
                href="https://github.com/rickhallett/thepit"
                target="_blank"
                rel="noreferrer"
                className="text-accent underline"
              >
                github.com/rickhallett/thepit
              </a>
              .
            </li>
          </ul>
        </section>

        <section className="flex flex-col gap-4">
          <h2 className="text-sm font-bold uppercase tracking-[0.2em]">
            11. Governing Law
          </h2>
          <p className="text-sm text-muted">
            These Terms shall be governed by and construed in accordance with the
            laws of England and Wales. Any disputes arising from or related to
            these Terms or your use of the Platform shall be subject to the
            exclusive jurisdiction of the courts of England and Wales.
          </p>
        </section>
      </div>
    </main>
  );
}
