export default function DisclaimerPage() {
  return (
    <main className="min-h-screen bg-background text-foreground">
      <div className="mx-auto flex min-h-screen max-w-4xl flex-col gap-6 px-6 py-12">
        <header className="border-b-2 border-foreground/70 pb-4">
          <p className="text-xs uppercase tracking-[0.4em] text-accent">
            Disclaimer
          </p>
          <h1 className="mt-3 font-sans text-3xl uppercase tracking-tight">
            Use at Your Own Risk
          </h1>
        </header>
        <p className="text-sm text-muted">
          THE PIT is an experimental, entertainment-first product. Outputs are
          generated by AI and may be incorrect, offensive, or inconsistent. Do
          not rely on responses for professional, medical, legal, or financial
          advice.
        </p>
        <p className="text-sm text-muted">
          By using the service you accept full responsibility for how you use
          and interpret the content.
        </p>
      </div>
    </main>
  );
}
